spring:
  data:
    mongodb:
      host: (host)
      port: (port)
      username: (username)
      password: (password)
      database: (database)
      authentication-database: (authentication-database)
    redis:
      host: (host)
      port: (port)
      password: (password)
